/// <reference path="typings/angular2/angular2.d.ts" />
import { ElementRef, Renderer, EventEmitter } from 'angular2/angular2';
export declare class NgGrid {
    private _ngEl;
    private _renderer;
    onDragStart: EventEmitter;
    onDrag: EventEmitter;
    onDragStop: EventEmitter;
    onResizeStart: EventEmitter;
    onResize: EventEmitter;
    onResizeStop: EventEmitter;
    colWidth: number;
    rowHeight: number;
    marginTop: number;
    marginRight: number;
    marginBottom: number;
    marginLeft: number;
    isDragging: boolean;
    isResizing: boolean;
    private _resizeEnable;
    private _dragEnable;
    private _items;
    private _draggingItem;
    private _resizingItem;
    private _resizeDirection;
    private _itemGrid;
    private _config;
    private _containerWidth;
    private _containerHeight;
    private _maxCols;
    private _maxRows;
    private _minWidth;
    private _minHeight;
    private _posOffset;
    private _adding;
    private _cascade;
    private static CONST_DEFAULT_CONFIG;
    config: any;
    constructor(_ngEl: ElementRef, _renderer: Renderer);
    setConfig(config: any): void;
    setMargins(margins: any): void;
    enableDrag(): void;
    disableDrag(): void;
    enableResize(): void;
    disableResize(): void;
    addItem(ngItem: NgGridItem): void;
    removeItem(ngItem: NgGridItem): void;
    private _onMouseDown(e);
    private _resizeStart(e);
    private _dragStart(e);
    private _onMouseMove(e);
    private _drag(e);
    private _resize(e);
    private _onMouseUp(e);
    private _dragStop(e);
    private _resizeStop(e);
    private _setAttr(name, val);
    private _maxGridSize(w, h);
    private _calculateGridSize(item);
    private _calculateGridPosition(item);
    private _checkGridCollision(pos, dims);
    private _getCollisions(pos, dims);
    private _fixGridCollisions(pos, dims);
    private _cascadeGrid(pos?, dims?);
    private _fixGridPosition(pos, dims);
    private _addToGrid(item);
    private _removeFromGrid(item);
    private _updateSize(col?, row?);
    private _filterGrid();
    private _getMaxRow();
    private _getMaxCol();
    private _getMousePosition(e);
    private _getAbsoluteMousePosition(e);
    private _getItemFromPosition(position);
}
export declare class NgGridItem {
    private _ngEl;
    private _renderer;
    private _ngGrid;
    private static CONST_DEFAULT_CONFIG;
    private _col;
    private _row;
    private _sizex;
    private _sizey;
    private _config;
    private _dragHandle;
    private _resizeHandle;
    private _elemWidth;
    private _elemHeight;
    private _elemLeft;
    private _elemTop;
    private _added;
    config: any;
    constructor(_ngEl: ElementRef, _renderer: Renderer, _ngGrid: NgGrid);
    canDrag(e: any): boolean;
    canResize(e: any): string;
    onMouseMove(e: any): void;
    getDragHandle(): string;
    getResizeHandle(): string;
    getDimensions(): {
        width: number;
        height: number;
    };
    getSize(): {
        x: number;
        y: number;
    };
    getPosition(): {
        left: number;
        top: number;
    };
    getGridPosition(): {
        col: number;
        row: number;
    };
    setConfig(config: any): void;
    setSize(x: any, y: any): void;
    setGridPosition(col: any, row: any): void;
    setPosition(x: any, y: any): void;
    setDimensions(w: any, h: any): void;
    private _recalculatePosition();
    private _recalculateDimensions();
    private _getMousePosition(e);
}
